spring:
  datasource:
    url: jdbc:mysql://graduation-project-db.cviiq428q4bx.ap-northeast-2.rds.amazonaws.com:3306/dlidam
    username: dlidam
    password: dlidam123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

token:
  jwt:
    access-key: thisistoolargeaccesstokenkeyfordummykeydataforlocal
    refresh-key: thisistoolargerefreshtokenkeyfordummykeydataforlocal
    access-expired-hours: 12
    refresh-expired-hours: 1460

oauth2:
  client:
    providers:
      kakao:
        admin-key: adminkey
        user-info-uri: https://kapi.kakao.com/v2/user/me
        user-unlink-uri: https://kapi.kakao.com/v1/user/unlink

fcm:
  enabled: true
  key:
    path: firebase/private-key.json