spring:
  datasource:
    url: jdbc:mysql://graduation-project-db.cviiq428q4bx.ap-northeast-2.rds.amazonaws.com:3306/dlidam
    username: dlidam
    password: dlidam123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

